 Stage C Quiz
 Data Description

 Predictive features:

1. 'tau1' to 'tau4': the reaction time of each network participant, a real value within the range 0.5 to 10 ('tau1' corresponds to the supplier node, 'tau2' to 'tau4' to the consumer nodes);

2. 'p1' to 'p4': nominal power produced (positive) or consumed (negative) by each network participant, a real value within the range -2.0 to -0.5 for consumers ('p2' to 'p4'). As the total power consumed equals the total power generated, p1 (supplier node) = - (p2 + p3 + p4);

3. 'g1' to 'g4': price elasticity coefficient for each network participant, a real value within the range 0.05 to 1.00 ('g1' corresponds to the supplier node, 'g2' to 'g4' to the consumer nodes; 'g' stands for 'gamma');

 Dependent variables:

1. 'stab': the maximum real part of the characteristic differential equation root (if positive, the system is linearly unstable; if negative, linearly stable);

2. 'stabf': a categorical (binary) label ('stable' or 'unstable').

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

In [2]:
dff=pd.read_csv('Data_for_UCI_named.csv')
dff

tau1      tau2      tau3      tau4        p1        p2        p3  \
0     2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1     9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2     8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3     0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4     3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   
...        ...       ...       ...       ...       ...       ...       ...   
9995  2.930406  9.487627  2.376523  6.187797  3.343416 -0.658054 -1.449106   
9996  3.392299  1.274827  2.954947  6.894759  4.349512 -1.663661 -0.952437   
9997  2.364034  2.842030  8.776391  1.008906  4.299976 -1.380719 -0.943884   
9998  9.631511  3.994398  2.757071  7.821347  2.514755 -0.966330 -0.649915   
9999  6.530527  6.781790  4.349695  8.673138  3.492807 -1.390285 -1.532193   

            p4        g1        g2        g3        g4      stab     stabf  
0    -1.723086  0.650456  0.859578  0.887445  0.958034  0.055347  unstable  
1    -1.255012  0.413441  0.862414  0.562139  0.781760 -0.005957    stable  
2    -0.920492  0.163041  0.766689  0.839444  0.109853  0.003471  unstable  
3    -0.997374  0.446209  0.976744  0.929381  0.362718  0.028871  unstable  
4    -0.554305  0.797110  0.455450  0.656947  0.820923  0.049860  unstable  
...        ...       ...       ...       ...       ...       ...       ...  
9995 -1.236256  0.601709  0.779642  0.813512  0.608385  0.023892  unstable  
9996 -1.733414  0.502079  0.567242  0.285880  0.366120 -0.025803    stable  
9997 -1.975373  0.487838  0.986505  0.149286  0.145984 -0.031810    stable  
9998 -0.898510  0.365246  0.587558  0.889118  0.818391  0.037789  unstable  
9999 -0.570329  0.073056  0.505441  0.378761  0.942631  0.045263  unstable  

[10000 rows x 14 columns]

In [3]:
df=dff.drop(['stab'], axis=1)
df

tau1      tau2      tau3      tau4        p1        p2        p3  \
0     2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1     9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2     8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3     0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4     3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   
...        ...       ...       ...       ...       ...       ...       ...   
9995  2.930406  9.487627  2.376523  6.187797  3.343416 -0.658054 -1.449106   
9996  3.392299  1.274827  2.954947  6.894759  4.349512 -1.663661 -0.952437   
9997  2.364034  2.842030  8.776391  1.008906  4.299976 -1.380719 -0.943884   
9998  9.631511  3.994398  2.757071  7.821347  2.514755 -0.966330 -0.649915   
9999  6.530527  6.781790  4.349695  8.673138  3.492807 -1.390285 -1.532193   

            p4        g1        g2        g3        g4     stabf  
0    -1.723086  0.650456  0.859578  0.887445  0.958034  unstable  
1    -1.255012  0.413441  0.862414  0.562139  0.781760    stable  
2    -0.920492  0.163041  0.766689  0.839444  0.109853  unstable  
3    -0.997374  0.446209  0.976744  0.929381  0.362718  unstable  
4    -0.554305  0.797110  0.455450  0.656947  0.820923  unstable  
...        ...       ...       ...       ...       ...       ...  
9995 -1.236256  0.601709  0.779642  0.813512  0.608385  unstable  
9996 -1.733414  0.502079  0.567242  0.285880  0.366120    stable  
9997 -1.975373  0.487838  0.986505  0.149286  0.145984    stable  
9998 -0.898510  0.365246  0.587558  0.889118  0.818391  unstable  
9999 -0.570329  0.073056  0.505441  0.378761  0.942631  unstable  

[10000 rows x 13 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   tau1    10000 non-null  float64
 1   tau2    10000 non-null  float64
 2   tau3    10000 non-null  float64
 3   tau4    10000 non-null  float64
 4   p1      10000 non-null  float64
 5   p2      10000 non-null  float64
 6   p3      10000 non-null  float64
 7   p4      10000 non-null  float64
 8   g1      10000 non-null  float64
 9   g2      10000 non-null  float64
 10  g3      10000 non-null  float64
 11  g4      10000 non-null  float64
 12  stabf   10000 non-null  object 
dtypes: float64(12), object(1)
memory usage: 1015.8+ KB


In [5]:
df['stabf'].value_counts()

unstable    6380
stable      3620
Name: stabf, dtype: int64

In [6]:
df.head()

tau1      tau2      tau3      tau4        p1        p2        p3  \
0  2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1  9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2  8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3  0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4  3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   

         p4        g1        g2        g3        g4     stabf  
0 -1.723086  0.650456  0.859578  0.887445  0.958034  unstable  
1 -1.255012  0.413441  0.862414  0.562139  0.781760    stable  
2 -0.920492  0.163041  0.766689  0.839444  0.109853  unstable  
3 -0.997374  0.446209  0.976744  0.929381  0.362718  unstable  
4 -0.554305  0.797110  0.455450  0.656947  0.820923  unstable

In [7]:
#features and label
x=df.drop(columns=['stabf'])

y=df['stabf']

In [8]:
#split the dataset to trai and set
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test=train_test_split(x, y, test_size=0.2, random_state=1)

print('x_train shape:{}'.format(x_train.shape))
print('y_train shape:{}'.format(y_train.shape))
print('x_test shape:{}'.format(x_test.shape))
print('y_test shape:{}'.format(y_test.shape))

x_train shape:(8000, 12)
y_train shape:(8000,)
x_test shape:(2000, 12)
y_test shape:(2000,)


In [9]:
#transform train and test set using standard scaler

from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)

x_train_scaled=scaler.transform(x_train)
x_test_scaled=scaler.transform(x_test)

In [10]:
#put the scaled sets into dataframe

x_train_sc=pd.DataFrame(x_train_scaled, columns=x_train.columns)
x_test_sc=pd.DataFrame(x_test_scaled, columns=x_test.columns)

# Building models

# RandomForestClassifier

In [11]:
#train a classifier
from sklearn.ensemble import RandomForestClassifier

rfc=RandomForestClassifier(random_state=1)

#fit the train
rfc.fit(x_train_sc, y_train)

RandomForestClassifier(random_state=1)

In [12]:
#make prediction on test set
pred1=rfc.predict(x_test_sc)

# Measuring model performance For RandomForestClassifier

In [13]:
#model accuracy
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_test, pred1)
print('Accuracy:{}'.format(round(accuracy*100),4))


from sklearn.metrics import recall_score, precision_score, f1_score, confusion_matrix, classification_report

#precission
precision=precision_score(y_test, pred1, pos_label='stable')
print('Precission Score:{}'.format(round(precision*100),2))

#recall
recall=recall_score(y_test, pred1, pos_label='stable')
print('Recall score:{}'.format(round(recall*100),2))

#f1_score
f1=f1_score(y_test, pred1, pos_label='stable')
print('F1_score:{}'.format(round(f1*100),2))

#classification report
print('Classification Report:\n', classification_report(y_test, pred1, digits=4))

#confussion matrix
conf_mat=confusion_matrix(y_test, pred1, labels=['unstable','stable'])
print('Confussion matrix:\n',conf_mat)

Accuracy:93
Precission Score:92
Recall score:88
F1_score:90
Classification Report:
               precision    recall  f1-score   support

      stable     0.9191    0.8778    0.8980       712
    unstable     0.9341    0.9573    0.9456      1288

    accuracy                         0.9290      2000
   macro avg     0.9266    0.9176    0.9218      2000
weighted avg     0.9288    0.9290    0.9286      2000

Confussion matrix:
 [[1233   55]
 [  87  625]]


In [14]:
print("Training set score:{:.3f}".format(rfc.score(x_train_sc, y_train)))
print("Test set score:{:.3f}".format(rfc.score(x_test_sc, y_test)))

Training set score:1.000
Test set score:0.929


# ExtraTreesClassifier

In [15]:
from sklearn.ensemble import ExtraTreesClassifier

etc=ExtraTreesClassifier(random_state=1)

#fit the train set
etc.fit(x_train_sc, y_train)

ExtraTreesClassifier(random_state=1)

In [16]:
#perdict on test set
etc_pred=etc.predict(x_test_sc)

# Measuring Model Performance for ExtraTreesClassifier

In [17]:
#model accuracy
from sklearn.metrics import accuracy_score
etc_accuracy=accuracy_score(y_test, etc_pred)
print('Accuracy:{}'.format(round(etc_accuracy*100),4))


from sklearn.metrics import recall_score, precision_score, f1_score, confusion_matrix, classification_report

#precission
etc_precision=precision_score(y_test, etc_pred, pos_label='stable')
print('Precission Score:{}'.format(round(etc_precision*100),2))

#recall
etc_recall=recall_score(y_test, etc_pred, pos_label='stable')
print('Recall score:{}'.format(round(etc_recall*100),2))

#f1_score
etc_f1=f1_score(y_test, etc_pred, pos_label='stable')
print('F1_score:{}'.format(round(etc_f1*100),2))

#classification report
print('Classification Report:\n', classification_report(y_test, etc_pred, digits=4))

#confussion matrix
etc_conf_mat=confusion_matrix(y_test, etc_pred)
print('Confussion matrix:\n',etc_conf_mat)

Accuracy:93
Precission Score:94
Recall score:85
F1_score:89
Classification Report:
               precision    recall  f1-score   support

      stable     0.9410    0.8511    0.8938       712
    unstable     0.9218    0.9705    0.9455      1288

    accuracy                         0.9280      2000
   macro avg     0.9314    0.9108    0.9197      2000
weighted avg     0.9287    0.9280    0.9271      2000

Confussion matrix:
 [[ 606  106]
 [  38 1250]]


In [18]:
print("Training set score:{:.3f}".format(etc.score(x_train_sc, y_train)))
print("Test set score:{:.3f}".format(etc.score(x_test_sc, y_test)))

Training set score:1.000
Test set score:0.928


# LightGBM Classifier

In [19]:
from lightgbm import LGBMClassifier

In [20]:
lgbm=LGBMClassifier(random_state=1)

In [21]:
#fit on train set
lgbm.fit(x_train_sc, y_train)

LGBMClassifier(random_state=1)

In [22]:
#predict on test set
lgbm_pred=lgbm.predict(x_test_sc)

# Model performance for LGBM Classifier

In [23]:
#model accuracy-
lgbm_acc=accuracy_score(y_test, lgbm_pred)
print('Accuracy Score:{}'.format(round(lgbm_acc*100),2))

#precision
lgbm_prec=precision_score(y_test, lgbm_pred, pos_label='stable')
print('Precision Score:{}'.format(round(lgbm_prec*100),2))

#Recall
lgbm_rec=recall_score(y_test, lgbm_pred, pos_label='stable')
print('Recall Score:{}'.format(round(lgbm_rec*100),2))

#f1 score
lgbm_f1=f1_score(y_test, lgbm_pred, pos_label='stable')
print('F1 Score:{}'.format(round(lgbm_f1*100),2))

#classification score
print('Classification Report:\n', classification_report(y_test, lgbm_pred, digits=4))

#confusion matrix
lgbm_cnf=confusion_matrix(y_test, lgbm_pred)
print('Confusion matrix:\n',lgbm_cnf)

Accuracy Score:94
Precision Score:93
Recall Score:90
F1 Score:91
Classification Report:
               precision    recall  f1-score   support

      stable     0.9276    0.9003    0.9138       712
    unstable     0.9458    0.9612    0.9534      1288

    accuracy                         0.9395      2000
   macro avg     0.9367    0.9307    0.9336      2000
weighted avg     0.9393    0.9395    0.9393      2000

Confusion matrix:
 [[ 641   71]
 [  50 1238]]


# XGBoost

In [24]:
from xgboost import XGBClassifier

In [25]:
xgb=XGBClassifier(random_state=1, base_score=0.5)

In [26]:
#introduce label encoder to solve error
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [27]:
ytrain=le.fit_transform(y_train)
y_test=le.fit_transform(y_test)

In [29]:
xgb.fit(x_train_sc, ytrain)

XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
              importance_type=None, interaction_constraints='',
              learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=100,
              n_jobs=0, num_parallel_tree=1, predictor='auto', random_state=1,
              reg_alpha=0, reg_lambda=1, ...)

In [30]:
#predict on test set
xgb_pred=xgb.predict(x_test_sc)

# Measuring Model Performance for XGB Classifier 

In [31]:
#model accuracy
xgb_acc=accuracy_score(y_test, xgb_pred)
print('Accuracy Score:{}'.format(round(xgb_acc*100),2))

#precision
xgb_pre=precision_score(y_test, xgb_pred)
print('Precision Score:{}'.format(round(xgb_pre*100),2))

#recall
xgb_rec=recall_score(y_test, xgb_pred)
print('Recall Score:{}'.format(round(xgb_rec*100),2))

#f1_score
f1=f1_score(y_test, xgb_pred)
print('F1 Score:{}'.format(round(f1*100),2))

#classification report
print('Classification  Report:\n', classification_report(y_test, xgb_pred, digits=4))

#confusion matrix
xgb_cnf=confusion_matrix(y_test, xgb_pred)
print('Confusion Matrix:\n', xgb_cnf)


Accuracy Score:95
Precision Score:95
Recall Score:97
F1 Score:96
Classification  Report:
               precision    recall  f1-score   support

           0     0.9351    0.9101    0.9224       712
           1     0.9510    0.9651    0.9580      1288

    accuracy                         0.9455      2000
   macro avg     0.9430    0.9376    0.9402      2000
weighted avg     0.9453    0.9455    0.9453      2000

Confusion Matrix:
 [[ 648   64]
 [  45 1243]]


# Improving ExtraTreeClassifier

In [32]:
#combination of hyperparameters
n_estimators = [50, 100, 300, 500, 1000]

min_samples_split = [2, 3, 5, 7, 9]

min_samples_leaf = [1, 2, 4, 6, 8]

max_features = ['auto', 'sqrt', 'log2', None] 

hyperparameter_grid = {'n_estimators': n_estimators,

                       'min_samples_leaf': min_samples_leaf,

                       'min_samples_split': min_samples_split,

                       'max_features': max_features}

In [33]:
from sklearn.model_selection import RandomizedSearchCV

#etc=ExtraTreesClassifier(random_state=1)

#set up randomsearch with 5 folds

randomcv=RandomizedSearchCV(estimator=etc,
                           param_distributions=hyperparameter_grid, cv=5, n_iter=10, scoring='accuracy',n_jobs=-1, verbose=1, random_state=1)

In [34]:
#fit on the training data
search = randomcv.fit(x_train_sc, y_train)


Fitting 5 folds for each of 10 candidates, totalling 50 fits


In [35]:
#get best parameters
search.best_params_

{'n_estimators': 1000,
 'min_samples_split': 2,
 'min_samples_leaf': 8,
 'max_features': None}

In [36]:
#evaluate ExtraTreeClassifier on test set using best params
etc2=ExtraTreesClassifier(max_features=None,
                         min_samples_leaf=8,
                         min_samples_split=2,
                         n_estimators=1000,
                         random_state=1)


#fit on train set
etc2.fit(x_train_sc, y_train)

ExtraTreesClassifier(max_features=None, min_samples_leaf=8, n_estimators=1000,
                     random_state=1)

In [88]:
etc2_pred=etc2.predict(x_test_sc)

In [38]:
#check feature importances
importance = etc2.feature_importances_

In [39]:
#print future importances
for i,v in enumerate(importance):
    print('Feature: %0d, Score: %.5f' % (i,v))

Feature: 0, Score: 0.13724
Feature: 1, Score: 0.14051
Feature: 2, Score: 0.13468
Feature: 3, Score: 0.13542
Feature: 4, Score: 0.00368
Feature: 5, Score: 0.00534
Feature: 6, Score: 0.00543
Feature: 7, Score: 0.00496
Feature: 8, Score: 0.10256
Feature: 9, Score: 0.10758
Feature: 10, Score: 0.11306
Feature: 11, Score: 0.10954


In [92]:
#get best score
search.best_score_

0.9241249999999999

In [93]:
#classification report
print('Classification Report:\n', classification_report(y_test, etc2_pred, digits=4))

Classification Report:
               precision    recall  f1-score   support

           0     0.9211    0.8694    0.8945       712
           1     0.9300    0.9589    0.9442      1288

    accuracy                         0.9270      2000
   macro avg     0.9256    0.9141    0.9193      2000
weighted avg     0.9268    0.9270    0.9265      2000

